// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApi.Helpers;

#nullable disable

namespace APITEST.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240930193430_update")]
    partial class update
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("WebApi.Entities.DepartmentTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("DepartmentTable");
                });

            modelBuilder.Entity("WebApi.Entities.FAQTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("answer")
                        .HasColumnType("longtext");

                    b.Property<string>("department")
                        .HasColumnType("longtext");

                    b.Property<string>("question")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("FAQTable");
                });

            modelBuilder.Entity("WebApi.Entities.GroupMessageTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DateAdded")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("group_id")
                        .HasColumnType("int");

                    b.Property<int>("mainTableFKId")
                        .HasColumnType("int");

                    b.Property<string>("message")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("mainTableFKId");

                    b.ToTable("GroupMessageTable");
                });

            modelBuilder.Entity("WebApi.Entities.GroupsTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("department")
                        .HasColumnType("longtext");

                    b.Property<string>("group_name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("GroupsTable");
                });

            modelBuilder.Entity("WebApi.Entities.MainTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Department")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordResetCode")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("PasswordResetExpiration")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ProfilePicture")
                        .HasColumnType("longtext");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("RefreshTokenExpiration")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Type")
                        .HasColumnType("longtext");

                    b.Property<string>("UserName")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("MainTable");
                });

            modelBuilder.Entity("WebApi.Entities.PersonalChatsTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DateAdded")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("answer")
                        .HasColumnType("longtext");

                    b.Property<string>("department")
                        .HasColumnType("longtext");

                    b.Property<string>("facultyType")
                        .HasColumnType("longtext");

                    b.Property<int>("mainTableFKId")
                        .HasColumnType("int");

                    b.Property<string>("question")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("mainTableFKId");

                    b.ToTable("PersonalChatsTable");
                });

            modelBuilder.Entity("WebApi.Entities.SubjectsTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("longtext");

                    b.Property<string>("Department")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("SubjectsTable");
                });

            modelBuilder.Entity("WebApi.Entities.GroupMessageTable", b =>
                {
                    b.HasOne("WebApi.Entities.MainTable", "MainTable")
                        .WithMany("GroupMessageTable")
                        .HasForeignKey("mainTableFKId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MainTable");
                });

            modelBuilder.Entity("WebApi.Entities.PersonalChatsTable", b =>
                {
                    b.HasOne("WebApi.Entities.MainTable", "MainTable")
                        .WithMany("PersonalChatsTable")
                        .HasForeignKey("mainTableFKId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MainTable");
                });

            modelBuilder.Entity("WebApi.Entities.MainTable", b =>
                {
                    b.Navigation("GroupMessageTable");

                    b.Navigation("PersonalChatsTable");
                });
#pragma warning restore 612, 618
        }
    }
}
